/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.address;

import org.junit.Test;

import com.cp.address.AddressBookMain;

import static org.junit.Assert.*;

public class AddressBookTest {
    
}
