/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.address;
import java.util.Scanner;

public class AddressBookMain {
	public static void main(String[] args) {
		System.out.println("Welcome to address book ---");

		Scanner in = new Scanner(System.in);
		AddressBook addressbook = new AddressBook();
		
        System.out.println("Enter 1 to add contact");
        System.out.println("Enter 2 to edit contact");
        System.out.println("Enter 3 to see addressbook details");
        System.out.println("Enter 4 to exit");
       
        int choice = in.nextInt();
        while(choice!= 4) {
	        if(choice == 1)
	        	addressbook.addContact();
	        else if(choice == 2)
	        	addressbook.editContact();
	        else if (choice == 3)
	        	addressbook.showDetails();
	        else if(choice == 4)
	        	break;
	        else{
	        	System.out.println("Please Enter Correct Choice Between 1-4 ");
	        }
	        System.out.println("Enter Choice ::");
	        choice = in.nextInt();
        }
		
	}
}
